# -*- coding: utf-8 -*-
"""FakeDATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVSpKR-gUG1h-FaLDvPsQ9gTFZv5S9yT
"""

#fake data should be imbalanced.
#as the real world data is also imbalanced.

!pip install faker

import pandas as pd
import uuid#to create unique id's
import random#to generate random nos
from faker import Faker

num_users = 100

features = ["id","gender","subscriber","name","rating"]
df = pd.DataFrame(columns = features)
df

df['id'] = [uuid.uuid4().node for i in range(num_users)]
df

print(df['id'].nunique() == num_users)#nunique() used to whether each id is unique or not.

genders = ["Male","Female"]
df['gender'] = random.choices(genders,weights = (45,45) ,k = num_users)
df

df.gender.value_counts()

choice = [True,False]
df['subscriber'] = random.choices(choice,k = num_users)

df

df.subscriber.value_counts()

faker = Faker(locale="en_us")
def name_gen(gender):#function to assign name males wale male ko female wale female ko.
  if gender == "Male":
    return faker.first_name_male()
  else:
    return faker.first_name_female()
  return faker.name()
#generating names for each user
df['name'] = [name_gen(gender) for gender in df['gender']]
df

ratings = [1,2,3,4,5]
df['rating'] = random.choices(ratings,k = num_users)
df
#

df.to_csv('ratings.csv')

