# -*- coding: utf-8 -*-
"""FillingMISSINGVALUES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmvOralyT5IsamOQa-qqMk6PUxMMD5pX
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/misssing11.csv")

df

df.isnull()#jha null values hai vha true dldiya hai
#jha nhi hai vha false

df.notnull()#yha ulta true false.

df[df['first_name'].notnull() & df['pre_movie_score'].isnull()]
#find the names of the people whose pre movie score is missing

#find the details of the prople where pre movie score in null

df[df['age'].notnull()&df['pre_movie_score'].isnull()]

df.isna().sum()#missing value count

df.isna().sum().sum()

#0 se rows drop hongi misisng values wali
#1 se columns
df1 = df.dropna(axis=0)

df1#rows kw liye

df2 = df.dropna(axis=1)#agar ek row mai saari missing values hai toh columns drop nhi krna
df2#columns ke liye

df1.isna().sum()

df4 = df.dropna(thresh=1)#This specifies the threshold for the minimum number of non-NaN values
#required to retain a row or column.
df4

df6 = df.fillna(10)#jo bhi value isme dalenge wo missing places mai chli jayegi

df6

df7 = df.fillna("heellooo")
df7

df['first_name'] = df['first_name'].fillna("Ram")

df

df['age'] = df['age'].fillna(df['age'].mean())
df

df['pre_movie_score'] = df['pre_movie_score'].fillna(df['pre_movie_score'].mean())
df

df['post_movie_score'] = df['post_movie_score'].fillna(df['post_movie_score'].median())
df

df['first_name'] = df['first_name'].mode()#we can use mode in caategorical columns
#it will return frequentily occuring value
df



